# Generated by Django 4.2.6 on 2023-10-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("library_app", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.CharField(max_length=255),
        ),
    ]
