# Generated by Django 4.2.6 on 2023-10-27 14:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("library_app", "0003_alter_book_author"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="borrowing",
            options={"ordering": ["-borrow_date"]},
        ),
    ]
